name: SubscriptionDeployment

on:
  workflow_call:

jobs:
  deployResources: 
    name: "Static validation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "Client ID: ${{ secrets.AZURE_CLIENT_ID }}"
          echo "Client Secret: ${{ secrets.AZURE_CLIENT_SECRET }}"
          echo "Tenant ID: ${{ secrets.AZURE_TENANT_ID }}"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: "Deploy bicep file"
        id: publish_step
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: ./packages/ipm-network/pipelines/scripts/subscriptionDeployment.ps1 -bicepFilePath "./main.bicep"